server:
  port: 8002
spring:
  application:
    name: ztcomsumer
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
